### ISSUE TITLE
nonstrict blocks protected migrations

### ISSUE THREAD

**Issue by tim-schilling** [aspiredu/django-safemigrate#45]
If nonstrict mode means there are no protections, it should run `migrate` without worrying about the safety status underneath for migrations.

**Comment by tim-schilling** [comment]
See https://github.com/aspiredu/django-safemigrate/pull/46 for test case

**Comment by tim-schilling** [comment]
@ryanhiebert But most post deploy operations are fixed in code. In order to work around this, I'd have to run a different command based on a env variable. It seems reasonable to have a way to disable safemigrate entirely.

**Comment by tim-schilling** [comment]
The other scenario this is helpful in is building up a non-development environment from scratch.

**Comment by ryanhiebert** [comment]
> building up a non-development environment from scratch.

For this one, I figured that the `postdeploy` script would reference `migrate` rather than safemigrate. It's not ready until its run completely. Does the release phase also run on the very first deploy? That would both make sense and be kind of defeating what I thought the purpose of the `postdeploy` script was in the first place. And if that's the case, then having a passthrough mode of some kind would be helpful.

**Comment by tim-schilling** [comment]
`postdeploy` is only for review apps.

**Comment by ryanhiebert** [comment]
I'd made some assumptions about what would be useful that I think you're proving are incorrect. Do you think the `nonstrict` mode, as documented, is perhaps a misfeature? Should we deprecate it in favor of a `disabled` mode? We could spell it `SAFEMIGRATE = False`. I like the boolean type better, but it would be more annoying to set from the environment.

**Comment by tim-schilling** [comment]
> Do you think the nonstrict mode, as documented, is perhaps a misfeature?

Yes, but I don't want to go through the deprecation process. It's easier to add a new setting value. Plus `nonstrict` doesn't make nearly as much sense as `disabled` for bypassing protections.
