### ISSUE TITLE
Allow multiple post-deployment migrations

### ISSUE THREAD

**Issue by tim-schilling** [aspiredu/django-safemigrate#5]
The current mechanism of safemigrate supports two types of migrations. Safe migrations which are run immediately before deployment and unsafe which are run sometime after, blocking any deployments that include migrations depending on the unsafe migration.

There is a third use-case in which some migrations need to be run after deployment, but should not block _some_ future migrations. For example, if a unique constraint needs to be created on a large table the unique index can be created concurrently in migration 1, then the constraint can be created on the table in migration 2. There is no reason that both migrations can't be deployed in the same build, but they need to be run separately. This case probably should block future migrations as the timing between these migrations requires manual intervention.

**Comment by ryanhiebert** [comment]
Currently, safe migrations are migrations that are expected to run before the deployment, and unsafe migrations are migrations that are expected to run after the deployment. Consecutive unsafe migrations will block, and fail deployment, even though there's no real reason that they should need to do that.

In principle, and disregarding the backward direction (which we always raise on), I see three useful categories of migrations: 1) migrations that are safe to run only before the deployment, 2) migrations that are safe to run only after the deployment, and 3) migrations that may be run either before or after the deployment without issue.

Currently, the default for a migration that is unmarked is that it is `safe = True`, indicating that it should be in category 1. Category 3 does not currently exist. I propose that we add add the third category as the default if nothing explicit is set on the migration. Migrations in this category will run before the deployment if possible, but will not block the deployment if they are after an unsafe migration.

I also propose that we relax the limitation on the 2nd category, unsafe migrations, so that they may accumulate without blocking the deployment. Only if a migration of the 1st category, safe migrations, follows a migration of the 2nd category, unsafe migrations, would `safemigrate` block the deployment, since a post-deployment inherently conflicts with a dependent pre-deployment migration.

Changing the default safety marking of a migration is a breaking change. Thus, this may also be a good time to make another breaking change, if we like it: to change the values of the `safe` command from boolean `True` and `False` to be an enum, like `Safe.before`, `Safe.after`, and the default (expected never specified) `Safe.always`.

I don't terribly care for enums if they can be avoided, but these names would provide some clarity to the meaning of the values that isn't present with the booleans. How does all this sound to you, @tim-schilling ?

**Comment by tim-schilling** [comment]
> Category 3 does not currently exist. I propose that we add add the third category as the default if nothing explicit is set on the migration. Migrations in this category will run before the deployment if possible, **but will not block the deployment if they are after an unsafe migration**.

I'm not sure how I feel about the highlighted portion. It seems like it's giving us a great way to shoot ourselves in the foot. I'd prefer to be a little more strict than to allow a forgetful developer to deploy a build that breaks because a migration didn't run. We both have forgotten to run unsafe migrations in the past, so it's fair to assume we would forget to specify a safe setting on a new migration and/or not check that the previous migrations are already run. Especially because (this just applies to our stack) our deployment/promoting process does not include any output about the migrations.

**Comment by ryanhiebert** [comment]
I agree that forgetfulness is to be guarded against if possible. Ideally, I'd like to require that the `safe` property is always set, and raise if it is not. However, that doesn't seem reasonable since 3rd party apps won't know about `safemigrate`, and cannot reasonably be expected to set `safe`.

Perhaps we could require migrations in declared (intended local) namespaces to always have the `safe` property set, avoiding the local forgetful developer, and have the default as `Safe.always` to allow 3rd party apps to be as flexible as possible? Or perhaps to have the apps declare themselves whether they should be expected to use the `safe` property?

**Comment by tim-schilling** [comment]
> Perhaps we could require migrations in declared (intended local) namespaces to always have the safe property set, avoiding the local forgetful developer, and have the default as Safe.always to allow 3rd party apps to be as flexible as possible? Or perhaps to have the apps declare themselves whether they should be expected to use the safe property?

I'm not sure how you'd do either of those things without requiring additional setup by the user.

Another option is to change the default to `Safe.after` then the user can adjust the environment variable to enforce the safety less strictly when they have 3rd party migrations to run if it's necessary.

**Comment by ryanhiebert** [comment]
> I'm not sure how you'd do either of those things without requiring additional setup by the user.

Both of those would be optional additional configuration by the user to enable the safety. The first idea would be a new setting, and the second would be a property on the `AppConfig` instance.

> Another option is to change the default to Safe.after

That would have been immediately untenable before the decision to allow `Safe.after` migrations to not block other `Safe.after` migrations, but with that objection out of the way, it may be equally as tenable a default as `Safe.before` has been. Or perhaps even more.

It could be a preferable default, because it just means that we never automatically run migrations that have not been declared safe to run before the code is shipped. There may be times that we _wish_ that we could change 3rd party migrations to run before, and that would require a further improvement if it did turn out to be the case that we wanted to have that capability. Still, this may be a more reasonable choice for the default.

With using `Safe.after` as the default, do you think it is worthwhile to have the `Safe.always` option? I still see utility in it, but its utility is diminished if it isn't the default, and I think you've brought up reasonable objections to it being the default. I think that I still like it, and I have got WIP that already has that option working on my local machine.

**Comment by tim-schilling** [comment]
> There may be times that we wish that we could change 3rd party migrations to run before, and that would require a further improvement if it did turn out to be the case that we wanted to have that capability.

Agreed and I thought about that. I know it's a solve-able problem, but I don't think it's one we need to solve now.

If you already have `Safe.always` built out, then I'm content keeping it in.

Side note, I think we should use `after_deploy` and `before_deploy`. The one additional word makes the setting much more understandable.

**Comment by ryanhiebert** [comment]
> Side note, I think we should use after_deploy and before_deploy

I think I still like `before` and `after`. Perhaps I'm just too steeped in this to get a newcomers perspective, but I'm having a hard time understanding what else someone might think `before` and `after` refer to except the deployment of the associated code. That's the problem we're trying to solve. And I am adding documentation of these, so I'll be sure to use the word "deploy" in the prose.

I also find the `_` a bit annoying, and the names a bit long for my taste. That could be mitigated with the names `predeploy` and `postdeploy`, since prefixes are more acceptable to use with the `_` than words.

Another option could be to use multiple aliases, to allow both `before` and `before_deploy` to be the same value. I'm not a huge fan of having more than one way to write things, though.

**Comment by ryanhiebert** [comment]
Maybe the clarity of "deploy" would be better applied to the name of the property on the migration? So you'd add `safe_deploy = Safe.before`?

**Comment by ryanhiebert** [comment]
Hmm. I think that `safe_deploy` could be more confusing than just `safe`, so that would further reenforce the need for the `before_deploy`. I'm thinking about what the `safe` property might intuitively mean for a migration, to see if there might be a name that would be more likely to be recognized as a useful idea from Django Developers, in case this idea ever could become part of Django core. I'm having trouble thinking of one, though.

Unless you have been persuaded by my desire for short names that `before` and `after` are sufficiently unambiguous, then I'm going to go ahead and follow your suggestion of changing those names to `before_deploy` and `after_deploy`.

**Comment by tim-schilling** [comment]
>  I'm having a hard time understanding what else someone might think before and after refer to except the deployment of the associated code.

**Comment by tim-schilling** [comment]
Sorry, no. I still think the additional context is worth lengthening the name.
